export interface StationSeed {
  name: string;
  type: 'PROPIA' | 'COLABORADORA';
  isFixedColaboradora?: boolean;
  order: number;
}

export const PROPIAS_STATIONS: StationSeed[] = [
  { name: 'ARCOS', type: 'PROPIA', order: 1 },
  { name: 'ALCUBILLAS', type: 'PROPIA', order: 2 },
  { name: 'TORREJON', type: 'PROPIA', order: 3 },
  { name: 'ARCOS JALON', type: 'PROPIA', order: 4 },
  { name: 'ALFAJARIN', type: 'PROPIA', order: 5 },
  { name: 'TORREMOCHA', type: 'PROPIA', order: 6 },
  { name: 'MADRID', type: 'PROPIA', order: 7 },
  { name: 'VALLECAS', type: 'PROPIA', order: 8 },
  { name: 'UCLES', type: 'PROPIA', order: 9 },
  { name: 'PAMPLONA', type: 'PROPIA', order: 10 },
  { name: 'HUMILLADERO', type: 'PROPIA', order: 11 },
  { name: 'BENAMEJI', type: 'PROPIA', order: 12 },
  { name: 'SORIA ALCUBILLAS', type: 'PROPIA', order: 13 },
  { name: 'ES RIBA-ROJA', type: 'PROPIA', order: 14 },
  { name: 'ALBUIXECH', type: 'PROPIA', order: 15 },
  { name: 'ES PISTA DE SILLA', type: 'PROPIA', order: 16 },
  { name: 'ES REAL DE GANDIA', type: 'PROPIA', order: 17 },
  { name: 'ES CHIVA', type: 'PROPIA', order: 18 },
  { name: 'ES ALBERIC', type: 'PROPIA', order: 19 },
  { name: 'CATARROJA', type: 'PROPIA', order: 20 },
];

export const COLABORADORA_STATIONS: StationSeed[] = [
  { name: 'Z.FRANCA', type: 'COLABORADORA', isFixedColaboradora: true, order: 21 },
  { name: 'BENAVENTE', type: 'COLABORADORA', isFixedColaboradora: true, order: 22 },
  { name: 'IRUN ZAISA III', type: 'COLABORADORA', isFixedColaboradora: true, order: 23 },
  { name: 'AVILESINA', type: 'COLABORADORA', isFixedColaboradora: true, order: 24 },
  { name: 'MERIDA', type: 'COLABORADORA', isFixedColaboradora: true, order: 25 },
  { name: 'SANCTI-SPIRITUS', type: 'COLABORADORA', isFixedColaboradora: true, order: 26 },
  { name: 'SAN VICENTE DEL PALACIO', type: 'COLABORADORA', isFixedColaboradora: true, order: 27 },
  { name: 'WATERY ARANDA', type: 'COLABORADORA', isFixedColaboradora: true, order: 28 },
  { name: 'PUERTO DE BARCELONA', type: 'COLABORADORA', isFixedColaboradora: true, order: 29 },
  { name: 'FEGOBLAN PONTEVEDRA', type: 'COLABORADORA', isFixedColaboradora: true, order: 30 },
  { name: 'VEGA DE VALCARCE', type: 'COLABORADORA', isFixedColaboradora: true, order: 31 },
  { name: 'HOILA TOLEDO', type: 'COLABORADORA', isFixedColaboradora: true, order: 32 },
  { name: 'PETREM FIGUERES', type: 'COLABORADORA', isFixedColaboradora: true, order: 33 },
  { name: 'ABRERA', type: 'COLABORADORA', order: 34 },
  { name: 'VALDEHERRERA', type: 'COLABORADORA', order: 35 },
  { name: 'EL CASAR', type: 'COLABORADORA', order: 36 },
  { name: 'VALDEMORO', type: 'COLABORADORA', order: 37 },
  { name: 'LA JOYOSA', type: 'COLABORADORA', order: 38 },
  { name: 'JUNDIZ NORPETROL', type: 'COLABORADORA', order: 39 },
  { name: 'OLIVERAL', type: 'COLABORADORA', order: 40 },
  { name: 'GUARROMAN', type: 'COLABORADORA', order: 41 },
  { name: 'VALDEPEÑAS', type: 'COLABORADORA', order: 42 },
  { name: 'TJOIL SEVILLA', type: 'COLABORADORA', order: 43 },
  { name: 'VILAMALLA', type: 'COLABORADORA', order: 44 },
  { name: 'TARRAGONA', type: 'COLABORADORA', order: 45 },
  { name: 'LACHAR', type: 'COLABORADORA', order: 46 },
  { name: 'LA CAMPANA', type: 'COLABORADORA', order: 47 },
  { name: 'RIBA-ROJA', type: 'COLABORADORA', order: 48 },
  { name: 'GOR', type: 'COLABORADORA', order: 49 },
  { name: 'PISTAL DE SILLA', type: 'COLABORADORA', order: 50 },
  { name: 'LLERS', type: 'COLABORADORA', order: 51 },
  { name: 'BARCELONA', type: 'COLABORADORA', order: 52 },
  { name: 'DARRO - A92', type: 'COLABORADORA', order: 53 },
  { name: 'MURCIA', type: 'COLABORADORA', order: 54 },
  { name: 'CARTAGENA', type: 'COLABORADORA', order: 55 },
  { name: 'NORIOIL', type: 'COLABORADORA', order: 56 },
  { name: 'HUELVA', type: 'COLABORADORA', order: 57 },
  { name: 'BERA', type: 'COLABORADORA', order: 58 },
  { name: 'GIRONA-CALSINA', type: 'COLABORADORA', order: 59 },
];

export const COLABORADORAS_STATIONS = COLABORADORA_STATIONS;

export const PRODUCTS = [
  { code: 'GOA', name: 'Gasóleo A', order: 1 },
  { code: 'GASOLINA', name: 'Gasolina 95', order: 2 },
  { code: 'GOA_PREMIUM', name: 'Gasóleo A Premium (+0.04€)', order: 3 },
  { code: 'HVO', name: 'HVO', order: 4 },
  { code: 'GASOLEO_B', name: 'Gasóleo B', order: 5 },
  { code: 'ADBLUE', name: 'AdBlue', order: 6 },
];

export const TARIFFS = [
  'SABANA DE PRECIOS',
  'TARIFA 12',
  'TARIFA 18',
  'T18 - PISTA DE SILLA',
  'TARIFA 24',
  'TARIFA 36',
  'T36 - PISTA DE SILLA',
  'ESPECIAL COMPLETO',
  'TARIFA 40',
  'TARIFA 42',
  'TARIFA 45',
  'TARIFA 50',
  'TARIFA 60',
  'T60 - PISTA DE SILLA',
  'AMAEXO',
  'NORIEGA',
  'E100',
  'TARIFA ECO',
  'DORADO',
  'HIQI',
  'NORPETROL 24',
  'ROR',
  'TARJETERA',
  'TAX MOVING 24',
  'TORTUGA',
  'TARIFA 15',
  'TARIFA 27',
  'EXOIL',
  'NORPETROL',
];
